[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nbscuid"
version = "0.0.1"
authors = [
  { name="Elena Romashkova", email="eromashkova@ucar.edu" },
]
description = "Notebook-Based, Super CUstomizable Infrastructure for Diagnostics"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

[project.urls]
source = "https://github.com/rmshkv/nbscuid"


[project.scripts]
nbscuid-run = "nbscuid.run_wrapper:run"
nbscuid-build = "nbscuid.build_wrapper:build"